### PR TITLE
fix tile_index_crawl.py default cdn

### PR DESCRIPTION
**Pull request by relud**
r? @oyiptong

### CODE REVIEW

**Comment by mostlygeek** [comment]
Why can't `cdn` be a straight URL without any cloudfront or S3 specifics in there?

**Comment by relud** [comment]
the specifics are just for setting reasonable defaults. when you specify an argument on the command line, it is just a url. this default change is to make sure we validate against s3, and not the cdn, because the cdn takes forever to update, so we want to validate against the tile index from s3, which is what is used by onyx anyway

**Comment by oyiptong** [comment]
r+

How long does the CDN take to update? In theory it's a read-through cache isn't it?

If there's new content, it will have a new filename, save for the index file, which is always accessed through S3

**Comment by relud** [comment]
"save for the index file" that's the only thing being accessed via the url provided to the script

**Comment by oyiptong** [comment]
awesome

**Pull request closed without merging**
