### PR TITLE
update alembic migration to respect ignore redshift option

### PR DESCRIPTION
**Pull request by relud**
r? @ncloudioj

### CODE REVIEW

**Comment by ncloudioj** [comment]
r+

**Comment by relud** [comment]
this doesn't need its own release, imo

**Comment by ncloudioj** [comment]
How about I merge and tag it as 2.1.7.1 for the upcoming production deploy?

**Comment by relud** [comment]
_shrug_ anything works for me, including just deploying 2.1.7 as it was to prod.

**Comment by ncloudioj** [comment]
ah, cool, thought it might incur some errors during the deploy without this guard.

k, merging it without bumping the version. Thanks.

**Pull request merged**
